# Generated by Django 3.2.15 on 2022-12-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_watchlist_platform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamplatform',
            old_name='url',
            new_name='path',
        ),
    ]
