# Generated by Django 4.0.3 on 2022-03-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_base_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='base_user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
