# Generated by Django 4.0.3 on 2022-03-21 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_base_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
